DeftCorgi/PP1_2018

- client/.gitignore
- client/README.md
- client/package-lock.json
- client/package.json
- client/public/index.html
- client/public/manifest.json
- client/src/App.js
- client/src/index.js
- client/src/registerServiceWorker.js
- package-lock.json
- package.json
- server.js
added react app
added backend server
added SOME dependencies
> Initial project setup

- client/src/components/MatchCard.js
- matchingAlgorithm/match.js
- routes/api.js
Fixed the api endpoint for the matching algorithm so it can be called appropriately.
> Connected basic matches

- client/src/components/MatchCard.js
- client/src/components/MatchMeter.js
- matchingAlgorithm/match.js
- matchingAlgorithm/matchCalculate.js
- matchingAlgorithm/test.js
- migrations/20180823072121-drop-responses.js
- migrations/20180823072254-recreate-responses.js
- models/responses.js
- routes/api.js
- seeders/20180822142011-users-seeder.js
First draft of the matching algorithm
Current issues:
(Make algorithm take id value, waiting for registration form so users always have responses to compare)
(Needs to filter users that the matching user has already interacted with, waiting for matching to be implemented)
Other changes:
Slightly altered matchmeter component, showed values as higher than the percentage represented,
Fixed the display names on match cards based on the new models.
> Matching algorithm

- client/src/components/MatchCard.js
- client/src/components/RegistrationForm.js
- client/src/pages/AboutUs.js
- client/src/pages/Home.js
- client/src/pages/Privacy.js
deleted some unused imports, added alt property to img tag
> cleaned up warnings on the client side

- routes/api.js
added:
/locales
/regions
to routes.api.
> Region locale api calls

- .gitignore
- client/src/App.js
- client/src/components/Content.js
- client/src/components/Footer.js
- client/src/components/Navbar.js
- client/src/routes.js
* Content component now takes children.
* Created AppSwitch component that handles Public/Protected routes depending on user auth status.
* Updated .gitignore with .DS_Store.
This should close #34
> Implemented auth routes and updated .gitignore

- client/src/routes.js
Fixes the register route logic
> Register route can be accessed by auth user

- client/src/components/Footer.js
- client/src/components/Navbar.js
- client/src/pages/AboutUs.js
- client/src/pages/Contact.js
- client/src/pages/Landing.js
- client/src/pages/Privacy.js
Made some components functional because they have no state and probably won't. Also refactored Navbar component.
> Stateless components

- client/public/index.html
- client/src/components/Footer.js
- client/src/components/Navbar.js
- client/src/pages/Home.js
- client/src/styles/css/App.css
- client/src/styles/css/Navbar.css
- client/src/styles/css/master.css
- client/src/styles/scss/App.scss
- client/src/styles/scss/Navbar.scss
This is not complete but merging sooner than later is preferred (changes in .container class).
> Navbar revamp

- client/src/components/Navbar.js
- client/src/pages/Landing.js
- client/src/redux/actions/user.js
- client/src/redux/reducers/user.js
- client/src/routes.js
* User can still access the pages: About, Contact etc.
> Prevent first time users from exiting the registration process.

- client/src/components/Navbar.js
- client/src/redux/actions/user.js
- client/src/redux/reducers/user.js
- client/src/routes.js
> Revert "Prevent first time users from exiting the registration process."

- client/src/components/Navbar.js
- client/src/pages/registration/QuestionAnswerForm.js
- client/src/styles/css/App.css
- client/src/styles/css/Landing.css
- client/src/styles/css/Navbar.css
- client/src/styles/css/Registration.css
- client/src/styles/css/master.css
- client/src/styles/scss/App.scss
- client/src/styles/scss/Footer.scss
- client/src/styles/scss/Landing.scss
- client/src/styles/scss/Navbar.scss
- client/src/styles/scss/Registration.scss
- client/src/styles/scss/_variables.scss
buttons with hover effects:
Facbook
Google
Discord
button1 tag.
> Hover button

- client/src/components/Navbar.js
- client/src/redux/actions/user.js
- client/src/redux/reducers/user.js
- client/src/routes.js
Fixes user state in redux and so fixes the conditionals on routing and navbar.
* It will make the problem of the server sometimes not returning user state very apparent
* Also will show the need for a splash screen like Slack has, or something similar (it takes a slight bit of time to get user from server upon refresh or new tab, etc.)
> Fixes user state

- routes/auth.js
Didn't fix the issue but whatever...
> Missing await?

- matchingAlgorithm/match.js
- models/locale.js
- models/region.js
- models/users.js
- userFunctions/userCalls.js
added locale and region outputs to various API calls
> Region locale outputs

- matchingAlgorithm/match.js
- models/locale.js
- models/region.js
- models/users.js
- userFunctions/userCalls.js
> Revert "Region locale outputs"

- client/src/components/MatchCard.js
- client/src/styles/css/MatchCard.css
- client/src/styles/css/Navbar.css
- client/src/styles/css/master.css
- client/src/styles/scss/MatchCard.scss
- client/src/styles/scss/Navbar.scss
accidentally made branch from navhover, sorry
> Like dislike button

- client/src/pages/Home.js
- client/src/redux/actions/pending.js
- client/src/redux/actions/user.js
- userFunctions/userCalls.js
* likes and dislikes will now refresh the pending dropdown
> updated api to return list of pendingMatches

- client/src/components/SelectSearch.js
- client/src/pages/registration/GameAndGenresForm.js
- client/src/redux/actions/games.js
- client/src/redux/actions/genres.js
- package-lock.json
- routes/api.js
- userFunctions/userCalls.js
* dummy data replaced with real API data
* bug fixes for SearchSelect component
> Rego games & redux list redux

- .gitignore
- client/src/components/MatchCard.js
- client/src/pages/Profile.js
- package-lock.json
- package.json
- routes/api.js
- userFunctions/userCalls.js
* enabled gcs uploading
* created new keysfile
* updated gitignore
* fixed matchcard to display user's pfp OR default
* updated profile page to dispay user's pfp OR default
> Registration pfp upload

- client/src/components/PendingDropdownMenu.js
- client/src/redux/actions/pending.js
- client/src/redux/actions/types.js
- client/src/redux/reducers/pending.js
* Remove pending user now reflects server-side.
* Added function documentation for pending redux actions.
> Implemented remove pending user, and added func docs.

- client/src/components/DocumentTitle.js
- client/src/pages/AboutUs.js
- client/src/pages/Contact.js
- client/src/pages/Home.js
- client/src/pages/Landing.js
- client/src/pages/Loading.js
- client/src/pages/Matches.js
- client/src/pages/NotFound.js
- client/src/pages/Privacy.js
- client/src/pages/Profile.js
Pages now have a proper document title.
> Added document titles

- client/src/components/DocumentTitle.js
- client/src/pages/AboutUs.js
- client/src/pages/Contact.js
- client/src/pages/Home.js
- client/src/pages/Landing.js
- client/src/pages/Loading.js
- client/src/pages/Matches.js
- client/src/pages/NotFound.js
- client/src/pages/Privacy.js
- client/src/pages/Profile.js
- client/src/pages/registration/ConfirmationForm.js
- client/src/pages/registration/GameAndGenresForm.js
* Fixed error on Home and Matches pages: 
`Warning: Can't call setState (or forceUpdate) on an unmounted component`.
* Fixed remaining warnings.
> Unmount error fix

- client/package.json
- client/src/pages/Matches.js
- client/src/pages/Profile.js
- client/src/styles/css/master.css
- client/src/styles/scss/Profile.scss
* Also added react-loading package as dep.
> Added loading indicators on Profile and Matches pages.

- client/src/components/DocumentTitle.js
- client/src/components/PendingDropdownMenu.js
- client/src/pages/Matches.js
- client/src/pages/MemberProfile.js
- client/src/pages/Profile.js
- client/src/redux/actions/pending.js
- client/src/redux/reducers/matched.js
- client/src/routes.js
- client/src/styles/css/AboutUs.css
- client/src/styles/css/Contact.css
- client/src/styles/css/Privacy.css
- client/src/styles/css/master.css
- client/src/styles/scss/AboutUs.scss
- client/src/styles/scss/Contact.scss
- client/src/styles/scss/Privacy.scss
* Added padding to contact and about pages.
* Added new member profile route.
* Profile Page now doesn't needlessly refetches data. Gets data from viewUser state if state has already been fetched.
* Matches page now doesn't refetch state needlessly.
* Modified dropdown to link to member's profile page.
* When pending user is pressed dropdown is toggled away.
* Member profile page is now completed more or less.
> Changes to persist state, and new members profile page.
